"""Regenerate ORIENTATION.md — the map of the codebase, for a reader who has
not got it.

    python3 tools/build_orientation.py

Written for an LLM with a small context window reading the project from a USB
drive. The problem it solves is specific and was observed: given one file and
no map, a reviewer invents plausible contents for the files it has not seen,
confidently and in detail. A map is far cheaper than the files.

GENERATED, not hand-kept, and from the source itself: every file in src/ opens
with a `##` summary line, so the table below is the code describing itself. A
hand-written map would be wrong within a week, which is the failure this whole
document exists to prevent.
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).parent.parent


def summary_of(text):
    """The file's own first doc line."""
    for line in text.splitlines():
        if line.startswith("## ") and len(line) > 6:
            return line[3:].strip()
    return ""


def inventory():
    rows = []
    for p in sorted(ROOT.joinpath("src").rglob("*.gd")):
        text = p.read_text(encoding="utf-8", errors="replace")
        rows.append({
            "path": p.relative_to(ROOT).as_posix(),
            "lines": text.count("\n") + 1,
            "tokens": len(text) // 4,
            "summary": summary_of(text),
        })
    return sorted(rows, key=lambda r: -r["lines"])


def find(pattern, *paths):
    """Where something is defined, as file:line."""
    for rel in paths:
        p = ROOT / rel
        if not p.exists():
            continue
        for i, line in enumerate(p.read_text(encoding="utf-8").splitlines(), 1):
            if re.search(pattern, line):
                return "%s:%d" % (rel, i)
    return "(not found)"


ENTRY_POINTS = [
    ("combat resolves", r"^func _attack\(", "src/sim/game_state.gd"),
    ("death consequences", r"^func _settle_death\(", "src/sim/game_state.gd"),
    ("a level is built", r"^func build_level\(", "src/sim/game_state.gd"),
    ("generation pipeline", r"^static func generate\(|^func generate\(", "src/sim/mapgen.gd"),
    ("turn order", r"^static func next_actor\(", "src/sim/scheduler.gd"),
    ("the player acts", r"^func player_move\(", "src/sim/game_state.gd"),
    ("what this square offers", r"^func actions_here\(", "src/sim/game_state.gd"),
    ("input arrives", r"^func _unhandled_key_input\(", "src/render/main.gd"),
    ("a pad becomes a keystroke", r"^func key_for\(", "src/render/gamepad.gd"),
    ("what may hold a gem", r"^func accepts_element\(", "src/sim/item.gd"),
    ("saving and loading", r"^func to_dict\(", "src/sim/game_state.gd"),
    ("the death log", r"^static func parse", "src/sim/morgue.gd"),
]


def main():
    rows = inventory()
    total_lines = sum(r["lines"] for r in rows)
    total_tokens = sum(r["tokens"] for r in rows)
    tests = ROOT / "tests/run_tests.gd"
    test_tokens = len(tests.read_text(encoding="utf-8")) // 4 if tests.exists() else 0

    out = []
    w = out.append
    w("# ORIENTATION.md — a map of OFR, for a reader who has not got the code")
    w("")
    w("Generated by `tools/build_orientation.py` from the source, so it cannot")
    w("drift. Every summary below is the file's own opening doc line.")
    w("")
    w("## Read this first")
    w("")
    w("**`DESIGN.md` explains why the code is shaped the way it is (~5k tokens).**")
    w("This file says where everything lives. Together they are about 8k tokens,")
    w("which is a small fraction of the project and most of what you need to")
    w("reason about it without guessing.")
    w("")
    w("```")
    w("  src/ alone          ~%3dk tokens" % (total_tokens // 1000))
    w("  the test suite      ~%3dk tokens" % (test_tokens // 1000))
    w("  the largest file    ~%3dk tokens   (%s)" % (
        rows[0]["tokens"] // 1000, rows[0]["path"]))
    w("  DESIGN.md + this    ~  8k tokens")
    w("```")
    w("")
    w("**If you have not read a file, say so rather than inferring its contents.**")
    w("This is not politeness, it is the failure mode this document was written")
    w("for: a reviewer given one file and no map produced a confident thirty-item")
    w("list of what a function did, of which six items were real. The map is here")
    w("so you can ask for the right file instead.")
    w("")
    w("## Where to look for a thing")
    w("")
    w("| you want | it is at |")
    w("|---|---|")
    for label, pattern, path in ENTRY_POINTS:
        w("| %s | `%s` |" % (label, find(pattern, path)))
    w("")
    w("## Four constraints that change what advice is correct")
    w("")
    w("1. **Determinism.** A seed must reproduce exactly, so the same seed must")
    w("   consume the same NUMBER of random draws. Any refactor that reorders")
    w("   generation silently changes every seeded run. There is a tool that")
    w("   hashes generated content across 20 seed/depth pairs")
    w("   (`tools/probes/fingerprint.gd`) so a change can be proven identical")
    w("   rather than assumed to be. Advice that ignores this is unsafe here.")
    w("2. **`src/sim` may not reference `src/render`.** That is what makes the")
    w("   whole game runnable headless, which is what makes ~1700 assertions")
    w("   possible. A proposed module that needs a renderer is not viable.")
    w("3. **One input vocabulary: keycodes.** Controllers are translated into")
    w("   synthetic keypresses and fed through the same door. Nothing downstream")
    w("   knows a pad exists. A synthetic press carries no modifiers, which has")
    w("   caused three separate bugs where an action was reachable only through")
    w("   a key a controller cannot produce.")
    w("4. **Comments carry reasoning, not description.** They record why a")
    w("   number is what it is, usually with the measurement behind it. They are")
    w("   the most information-dense part of the codebase; skipping them to save")
    w("   context will cost more than it saves.")
    w("")
    w("## Before proposing that something be split out")
    w("")
    w("Measure what the code REACHES FOR, not what its constants are named.")
    w("Constants clustering is not evidence that behaviour clusters. Measured on")
    w("this codebase: a proposed light module needed 11 fields of the central")
    w("object, a brazier module 9 across 14 functions. Those are not modules,")
    w("they are the same code with a prefix typed in front of every line — and")
    w("two objects that can disagree about one piece of state is the bug class")
    w("this project spends most of its effort preventing.")
    w("")
    w("The one extraction that passed that test reached for nothing at all:")
    w("`src/sim/threat.gd`, pure arithmetic over a depth and a cell count.")
    w("")
    w("## The files")
    w("")
    w("%d files, %d lines." % (len(rows), total_lines))
    w("")
    w("| file | lines | ~tokens | what it is |")
    w("|---|---|---|---|")
    for r in rows:
        w("| `%s` | %d | %dk | %s |" % (
            r["path"], r["lines"], max(r["tokens"] // 1000, 1), r["summary"]))
    w("")
    w("## Not in src/")
    w("")
    w("- `tests/run_tests.gd` — the suite. Large, and worth reading only for a")
    w("  specific question; the practices it embodies are in `DESIGN.md`.")
    w("- `tools/` — build scripts, publishing, and measurement probes. The probes")
    w("  answer questions rather than asserting; several findings quoted in")
    w("  `DESIGN.md` came from them.")
    w("- `assets/vaults/*.txt` — hand-authored rooms, a grid of characters with a")
    w("  small metadata header, validated by a linter in the suite.")

    path = ROOT / "ORIENTATION.md"
    path.write_text("\n".join(out) + "\n", encoding="utf-8")
    print("wrote %s (%d lines, ~%dk tokens)" % (
        path.name, len(out), len("\n".join(out)) // 4000))


if __name__ == "__main__":
    main()
